# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/anton/vomid/libvomid

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/anton/vomid/libvomid

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/anton/vomid/libvomid/CMakeFiles /home/anton/vomid/libvomid/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/anton/vomid/libvomid/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tester

# Build rule for target.
tester: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tester
.PHONY : tester

# fast build rule for target.
tester/fast:
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/build
.PHONY : tester/fast

#=============================================================================
# Target rules for targets named vomid

# Build rule for target.
vomid: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vomid
.PHONY : vomid

# fast build rule for target.
vomid/fast:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/build
.PHONY : vomid/fast

src/3rdparty/sha1/sha1.o: src/3rdparty/sha1/sha1.c.o
.PHONY : src/3rdparty/sha1/sha1.o

# target to build an object file
src/3rdparty/sha1/sha1.c.o:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/3rdparty/sha1/sha1.c.o
.PHONY : src/3rdparty/sha1/sha1.c.o

src/3rdparty/sha1/sha1.i: src/3rdparty/sha1/sha1.c.i
.PHONY : src/3rdparty/sha1/sha1.i

# target to preprocess a source file
src/3rdparty/sha1/sha1.c.i:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/3rdparty/sha1/sha1.c.i
.PHONY : src/3rdparty/sha1/sha1.c.i

src/3rdparty/sha1/sha1.s: src/3rdparty/sha1/sha1.c.s
.PHONY : src/3rdparty/sha1/sha1.s

# target to generate assembly for a file
src/3rdparty/sha1/sha1.c.s:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/3rdparty/sha1/sha1.c.s
.PHONY : src/3rdparty/sha1/sha1.c.s

src/bst.o: src/bst.c.o
.PHONY : src/bst.o

# target to build an object file
src/bst.c.o:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/bst.c.o
.PHONY : src/bst.c.o

src/bst.i: src/bst.c.i
.PHONY : src/bst.i

# target to preprocess a source file
src/bst.c.i:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/bst.c.i
.PHONY : src/bst.c.i

src/bst.s: src/bst.c.s
.PHONY : src/bst.s

# target to generate assembly for a file
src/bst.c.s:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/bst.c.s
.PHONY : src/bst.c.s

src/channel.o: src/channel.c.o
.PHONY : src/channel.o

# target to build an object file
src/channel.c.o:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/channel.c.o
.PHONY : src/channel.c.o

src/channel.i: src/channel.c.i
.PHONY : src/channel.i

# target to preprocess a source file
src/channel.c.i:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/channel.c.i
.PHONY : src/channel.c.i

src/channel.s: src/channel.c.s
.PHONY : src/channel.s

# target to generate assembly for a file
src/channel.c.s:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/channel.c.s
.PHONY : src/channel.c.s

src/export.o: src/export.c.o
.PHONY : src/export.o

# target to build an object file
src/export.c.o:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/export.c.o
.PHONY : src/export.c.o

src/export.i: src/export.c.i
.PHONY : src/export.i

# target to preprocess a source file
src/export.c.i:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/export.c.i
.PHONY : src/export.c.i

src/export.s: src/export.c.s
.PHONY : src/export.s

# target to generate assembly for a file
src/export.c.s:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/export.c.s
.PHONY : src/export.c.s

src/file.o: src/file.c.o
.PHONY : src/file.o

# target to build an object file
src/file.c.o:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/file.c.o
.PHONY : src/file.c.o

src/file.i: src/file.c.i
.PHONY : src/file.i

# target to preprocess a source file
src/file.c.i:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/file.c.i
.PHONY : src/file.c.i

src/file.s: src/file.c.s
.PHONY : src/file.s

# target to generate assembly for a file
src/file.c.s:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/file.c.s
.PHONY : src/file.c.s

src/hal.o: src/hal.c.o
.PHONY : src/hal.o

# target to build an object file
src/hal.c.o:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/hal.c.o
.PHONY : src/hal.c.o

src/hal.i: src/hal.c.i
.PHONY : src/hal.i

# target to preprocess a source file
src/hal.c.i:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/hal.c.i
.PHONY : src/hal.c.i

src/hal.s: src/hal.c.s
.PHONY : src/hal.s

# target to generate assembly for a file
src/hal.c.s:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/hal.c.s
.PHONY : src/hal.c.s

src/hal_alsa.o: src/hal_alsa.c.o
.PHONY : src/hal_alsa.o

# target to build an object file
src/hal_alsa.c.o:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/hal_alsa.c.o
.PHONY : src/hal_alsa.c.o

src/hal_alsa.i: src/hal_alsa.c.i
.PHONY : src/hal_alsa.i

# target to preprocess a source file
src/hal_alsa.c.i:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/hal_alsa.c.i
.PHONY : src/hal_alsa.c.i

src/hal_alsa.s: src/hal_alsa.c.s
.PHONY : src/hal_alsa.s

# target to generate assembly for a file
src/hal_alsa.c.s:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/hal_alsa.c.s
.PHONY : src/hal_alsa.c.s

src/hal_posix.o: src/hal_posix.c.o
.PHONY : src/hal_posix.o

# target to build an object file
src/hal_posix.c.o:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/hal_posix.c.o
.PHONY : src/hal_posix.c.o

src/hal_posix.i: src/hal_posix.c.i
.PHONY : src/hal_posix.i

# target to preprocess a source file
src/hal_posix.c.i:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/hal_posix.c.i
.PHONY : src/hal_posix.c.i

src/hal_posix.s: src/hal_posix.c.s
.PHONY : src/hal_posix.s

# target to generate assembly for a file
src/hal_posix.c.s:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/hal_posix.c.s
.PHONY : src/hal_posix.c.s

src/hal_win32.o: src/hal_win32.c.o
.PHONY : src/hal_win32.o

# target to build an object file
src/hal_win32.c.o:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/hal_win32.c.o
.PHONY : src/hal_win32.c.o

src/hal_win32.i: src/hal_win32.c.i
.PHONY : src/hal_win32.i

# target to preprocess a source file
src/hal_win32.c.i:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/hal_win32.c.i
.PHONY : src/hal_win32.c.i

src/hal_win32.s: src/hal_win32.c.s
.PHONY : src/hal_win32.s

# target to generate assembly for a file
src/hal_win32.c.s:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/hal_win32.c.s
.PHONY : src/hal_win32.c.s

src/import.o: src/import.c.o
.PHONY : src/import.o

# target to build an object file
src/import.c.o:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/import.c.o
.PHONY : src/import.c.o

src/import.i: src/import.c.i
.PHONY : src/import.i

# target to preprocess a source file
src/import.c.i:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/import.c.i
.PHONY : src/import.c.i

src/import.s: src/import.c.s
.PHONY : src/import.s

# target to generate assembly for a file
src/import.c.s:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/import.c.s
.PHONY : src/import.c.s

src/map.o: src/map.c.o
.PHONY : src/map.o

# target to build an object file
src/map.c.o:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/map.c.o
.PHONY : src/map.c.o

src/map.i: src/map.c.i
.PHONY : src/map.i

# target to preprocess a source file
src/map.c.i:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/map.c.i
.PHONY : src/map.c.i

src/map.s: src/map.c.s
.PHONY : src/map.s

# target to generate assembly for a file
src/map.c.s:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/map.c.s
.PHONY : src/map.c.s

src/midi.o: src/midi.c.o
.PHONY : src/midi.o

# target to build an object file
src/midi.c.o:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/midi.c.o
.PHONY : src/midi.c.o

src/midi.i: src/midi.c.i
.PHONY : src/midi.i

# target to preprocess a source file
src/midi.c.i:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/midi.c.i
.PHONY : src/midi.c.i

src/midi.s: src/midi.c.s
.PHONY : src/midi.s

# target to generate assembly for a file
src/midi.c.s:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/midi.c.s
.PHONY : src/midi.c.s

src/note.o: src/note.c.o
.PHONY : src/note.o

# target to build an object file
src/note.c.o:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/note.c.o
.PHONY : src/note.c.o

src/note.i: src/note.c.i
.PHONY : src/note.i

# target to preprocess a source file
src/note.c.i:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/note.c.i
.PHONY : src/note.c.i

src/note.s: src/note.c.s
.PHONY : src/note.s

# target to generate assembly for a file
src/note.c.s:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/note.c.s
.PHONY : src/note.c.s

src/notesystem.o: src/notesystem.c.o
.PHONY : src/notesystem.o

# target to build an object file
src/notesystem.c.o:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/notesystem.c.o
.PHONY : src/notesystem.c.o

src/notesystem.i: src/notesystem.c.i
.PHONY : src/notesystem.i

# target to preprocess a source file
src/notesystem.c.i:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/notesystem.c.i
.PHONY : src/notesystem.c.i

src/notesystem.s: src/notesystem.c.s
.PHONY : src/notesystem.s

# target to generate assembly for a file
src/notesystem.c.s:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/notesystem.c.s
.PHONY : src/notesystem.c.s

src/play.o: src/play.c.o
.PHONY : src/play.o

# target to build an object file
src/play.c.o:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/play.c.o
.PHONY : src/play.c.o

src/play.i: src/play.c.i
.PHONY : src/play.i

# target to preprocess a source file
src/play.c.i:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/play.c.i
.PHONY : src/play.c.i

src/play.s: src/play.c.s
.PHONY : src/play.s

# target to generate assembly for a file
src/play.c.s:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/play.c.s
.PHONY : src/play.c.s

src/pool.o: src/pool.c.o
.PHONY : src/pool.o

# target to build an object file
src/pool.c.o:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/pool.c.o
.PHONY : src/pool.c.o

src/pool.i: src/pool.c.i
.PHONY : src/pool.i

# target to preprocess a source file
src/pool.c.i:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/pool.c.i
.PHONY : src/pool.c.i

src/pool.s: src/pool.c.s
.PHONY : src/pool.s

# target to generate assembly for a file
src/pool.c.s:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/pool.c.s
.PHONY : src/pool.c.s

src/stack.o: src/stack.c.o
.PHONY : src/stack.o

# target to build an object file
src/stack.c.o:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/stack.c.o
.PHONY : src/stack.c.o

src/stack.i: src/stack.c.i
.PHONY : src/stack.i

# target to preprocess a source file
src/stack.c.i:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/stack.c.i
.PHONY : src/stack.c.i

src/stack.s: src/stack.c.s
.PHONY : src/stack.s

# target to generate assembly for a file
src/stack.c.s:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/stack.c.s
.PHONY : src/stack.c.s

src/track.o: src/track.c.o
.PHONY : src/track.o

# target to build an object file
src/track.c.o:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/track.c.o
.PHONY : src/track.c.o

src/track.i: src/track.c.i
.PHONY : src/track.i

# target to preprocess a source file
src/track.c.i:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/track.c.i
.PHONY : src/track.c.i

src/track.s: src/track.c.s
.PHONY : src/track.s

# target to generate assembly for a file
src/track.c.s:
	$(MAKE) -f CMakeFiles/vomid.dir/build.make CMakeFiles/vomid.dir/src/track.c.s
.PHONY : src/track.c.s

test/bst.o: test/bst.c.o
.PHONY : test/bst.o

# target to build an object file
test/bst.c.o:
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/test/bst.c.o
.PHONY : test/bst.c.o

test/bst.i: test/bst.c.i
.PHONY : test/bst.i

# target to preprocess a source file
test/bst.c.i:
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/test/bst.c.i
.PHONY : test/bst.c.i

test/bst.s: test/bst.c.s
.PHONY : test/bst.s

# target to generate assembly for a file
test/bst.c.s:
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/test/bst.c.s
.PHONY : test/bst.c.s

test/file.o: test/file.c.o
.PHONY : test/file.o

# target to build an object file
test/file.c.o:
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/test/file.c.o
.PHONY : test/file.c.o

test/file.i: test/file.c.i
.PHONY : test/file.i

# target to preprocess a source file
test/file.c.i:
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/test/file.c.i
.PHONY : test/file.c.i

test/file.s: test/file.c.s
.PHONY : test/file.s

# target to generate assembly for a file
test/file.c.s:
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/test/file.c.s
.PHONY : test/file.c.s

test/import.o: test/import.c.o
.PHONY : test/import.o

# target to build an object file
test/import.c.o:
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/test/import.c.o
.PHONY : test/import.c.o

test/import.i: test/import.c.i
.PHONY : test/import.i

# target to preprocess a source file
test/import.c.i:
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/test/import.c.i
.PHONY : test/import.c.i

test/import.s: test/import.c.s
.PHONY : test/import.s

# target to generate assembly for a file
test/import.c.s:
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/test/import.c.s
.PHONY : test/import.c.s

test/map.o: test/map.c.o
.PHONY : test/map.o

# target to build an object file
test/map.c.o:
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/test/map.c.o
.PHONY : test/map.c.o

test/map.i: test/map.c.i
.PHONY : test/map.i

# target to preprocess a source file
test/map.c.i:
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/test/map.c.i
.PHONY : test/map.c.i

test/map.s: test/map.c.s
.PHONY : test/map.s

# target to generate assembly for a file
test/map.c.s:
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/test/map.c.s
.PHONY : test/map.c.s

test/native-check.o: test/native-check.c.o
.PHONY : test/native-check.o

# target to build an object file
test/native-check.c.o:
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/test/native-check.c.o
.PHONY : test/native-check.c.o

test/native-check.i: test/native-check.c.i
.PHONY : test/native-check.i

# target to preprocess a source file
test/native-check.c.i:
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/test/native-check.c.i
.PHONY : test/native-check.c.i

test/native-check.s: test/native-check.c.s
.PHONY : test/native-check.s

# target to generate assembly for a file
test/native-check.c.s:
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/test/native-check.c.s
.PHONY : test/native-check.c.s

test/tester.o: test/tester.c.o
.PHONY : test/tester.o

# target to build an object file
test/tester.c.o:
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/test/tester.c.o
.PHONY : test/tester.c.o

test/tester.i: test/tester.c.i
.PHONY : test/tester.i

# target to preprocess a source file
test/tester.c.i:
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/test/tester.c.i
.PHONY : test/tester.c.i

test/tester.s: test/tester.c.s
.PHONY : test/tester.s

# target to generate assembly for a file
test/tester.c.s:
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/test/tester.c.s
.PHONY : test/tester.c.s

test/track.o: test/track.c.o
.PHONY : test/track.o

# target to build an object file
test/track.c.o:
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/test/track.c.o
.PHONY : test/track.c.o

test/track.i: test/track.c.i
.PHONY : test/track.i

# target to preprocess a source file
test/track.c.i:
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/test/track.c.i
.PHONY : test/track.c.i

test/track.s: test/track.c.s
.PHONY : test/track.s

# target to generate assembly for a file
test/track.c.s:
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/test/track.c.s
.PHONY : test/track.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... tester"
	@echo "... vomid"
	@echo "... src/3rdparty/sha1/sha1.o"
	@echo "... src/3rdparty/sha1/sha1.i"
	@echo "... src/3rdparty/sha1/sha1.s"
	@echo "... src/bst.o"
	@echo "... src/bst.i"
	@echo "... src/bst.s"
	@echo "... src/channel.o"
	@echo "... src/channel.i"
	@echo "... src/channel.s"
	@echo "... src/export.o"
	@echo "... src/export.i"
	@echo "... src/export.s"
	@echo "... src/file.o"
	@echo "... src/file.i"
	@echo "... src/file.s"
	@echo "... src/hal.o"
	@echo "... src/hal.i"
	@echo "... src/hal.s"
	@echo "... src/hal_alsa.o"
	@echo "... src/hal_alsa.i"
	@echo "... src/hal_alsa.s"
	@echo "... src/hal_posix.o"
	@echo "... src/hal_posix.i"
	@echo "... src/hal_posix.s"
	@echo "... src/hal_win32.o"
	@echo "... src/hal_win32.i"
	@echo "... src/hal_win32.s"
	@echo "... src/import.o"
	@echo "... src/import.i"
	@echo "... src/import.s"
	@echo "... src/map.o"
	@echo "... src/map.i"
	@echo "... src/map.s"
	@echo "... src/midi.o"
	@echo "... src/midi.i"
	@echo "... src/midi.s"
	@echo "... src/note.o"
	@echo "... src/note.i"
	@echo "... src/note.s"
	@echo "... src/notesystem.o"
	@echo "... src/notesystem.i"
	@echo "... src/notesystem.s"
	@echo "... src/play.o"
	@echo "... src/play.i"
	@echo "... src/play.s"
	@echo "... src/pool.o"
	@echo "... src/pool.i"
	@echo "... src/pool.s"
	@echo "... src/stack.o"
	@echo "... src/stack.i"
	@echo "... src/stack.s"
	@echo "... src/track.o"
	@echo "... src/track.i"
	@echo "... src/track.s"
	@echo "... test/bst.o"
	@echo "... test/bst.i"
	@echo "... test/bst.s"
	@echo "... test/file.o"
	@echo "... test/file.i"
	@echo "... test/file.s"
	@echo "... test/import.o"
	@echo "... test/import.i"
	@echo "... test/import.s"
	@echo "... test/map.o"
	@echo "... test/map.i"
	@echo "... test/map.s"
	@echo "... test/native-check.o"
	@echo "... test/native-check.i"
	@echo "... test/native-check.s"
	@echo "... test/tester.o"
	@echo "... test/tester.i"
	@echo "... test/tester.s"
	@echo "... test/track.o"
	@echo "... test/track.i"
	@echo "... test/track.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

