#define bool_t vmd_bool_t
#define bst_begin vmd_bst_begin
#define bst_bound vmd_bst_bound
#define bst_change vmd_bst_change
#define bst_clear vmd_bst_clear
#define bst_cmp_t vmd_bst_cmp_t
#define bst_commit vmd_bst_commit
#define bst_empty vmd_bst_empty
#define bst_end vmd_bst_end
#define bst_erase vmd_bst_erase
#define bst_erase_range vmd_bst_erase_range
#define bst_find vmd_bst_find
#define bst_fini vmd_bst_fini
#define bst_init vmd_bst_init
#define bst_insert vmd_bst_insert
#define bst_lower_bound vmd_bst_lower_bound
#define bst_next vmd_bst_next
#define bst_node vmd_bst_node
#define bst_node_adj vmd_bst_node_adj
#define bst_node_child_most vmd_bst_node_child_most
#define bst_node_is_end vmd_bst_node_is_end
#define bst_node_leftmost vmd_bst_node_leftmost
#define bst_node_next vmd_bst_node_next
#define bst_node_prev vmd_bst_node_prev
#define bst_node_rightmost vmd_bst_node_rightmost
#define bst_node_t vmd_bst_node_t
#define bst_prev vmd_bst_prev
#define bst_revert vmd_bst_revert
#define bst_rev_t vmd_bst_rev_t
#define bst_root vmd_bst_root
#define bst_size vmd_bst_size
#define bst_t vmd_bst_t
#define bst_update vmd_bst_update
#define bst_upd_t vmd_bst_upd_t
#define bst_upper_bound vmd_bst_upper_bound
#define cctrl_info vmd_cctrl_info
#define CCTRL_PITCHWHEEL VMD_CCTRL_PITCHWHEEL
#define CCTRL_PROGRAM VMD_CCTRL_PROGRAM
#define CCTRLS VMD_CCTRLS
#define CHANMASK_ALL VMD_CHANMASK_ALL
#define CHANMASK_DRUMS VMD_CHANMASK_DRUMS
#define CHANMASK_NODRUMS VMD_CHANMASK_NODRUMS
#define chanmask_t vmd_chanmask_t
#define channel_commit vmd_channel_commit
#define channel_create vmd_channel_create
#define channel_destroy vmd_channel_destroy
#define channel_fini vmd_channel_fini
#define channel_init vmd_channel_init
#define channel_note vmd_channel_note
#define channel_range vmd_channel_range
#define channel_rev_t vmd_channel_rev_t
#define CHANNELS VMD_CHANNELS
#define channel_t vmd_channel_t
#define channel_update vmd_channel_update
#define CMP VMD_CMP
#define copy_note vmd_copy_note
#define CTRL_BALANCE VMD_CTRL_BALANCE
#define CTRL_CONTROLLERS_OFF VMD_CTRL_CONTROLLERS_OFF
#define CTRL_EXPRESSION VMD_CTRL_EXPRESSION
#define ctrl_info_t vmd_ctrl_info_t
#define CTRL_NOTES_OFF VMD_CTRL_NOTES_OFF
#define CTRL_PAN VMD_CTRL_PAN
#define CTRLS VMD_CTRLS
#define CTRL_VOLUME VMD_CTRL_VOLUME
#define DEFAULT_VELOCITY VMD_DEFAULT_VELOCITY
#define DEFINE_DESTROY VMD_DEFINE_DESTROY
#define DEFINE_RANGE_FN VMD_DEFINE_RANGE_FN
#define delay_clb_t vmd_delay_clb_t
#define device_clb_t vmd_device_clb_t
#define DEVICE_TYPES VMD_DEVICE_TYPES
#define DO_JOIN VMD_DO_JOIN
#define DO_JOIN2 VMD_DO_JOIN2
#define DO_STRINGIFY VMD_DO_STRINGIFY
#define dtime_clb_t vmd_dtime_clb_t
#define enum_devices vmd_enum_devices
#define erase_note vmd_erase_note
#define erase_notes vmd_erase_notes
#define ERROR VMD_ERROR
#define event_clb_t vmd_event_clb_t
#define FALSE VMD_FALSE
#define fctrl_info vmd_fctrl_info
#define FCTRLS VMD_FCTRLS
#define FCTRL_TEMPO VMD_FCTRL_TEMPO
#define FCTRL_TIMESIG VMD_FCTRL_TIMESIG
#define file_commit vmd_file_commit
#define file_copy_string vmd_file_copy_string
#define file_export vmd_file_export
#define file_export_f vmd_file_export_f
#define file_fini vmd_file_fini
#define file_flatten vmd_file_flatten
#define file_import vmd_file_import
#define file_import_f vmd_file_import_f
#define file_init vmd_file_init
#define file_length vmd_file_length
#define file_measure vmd_file_measure
#define file_measure_at vmd_file_measure_at
#define file_measures vmd_file_measures
#define file_play vmd_file_play
#define file_play_ vmd_file_play_
#define file_rev_t vmd_file_rev_t
#define file_t vmd_file_t
#define file_update vmd_file_update
#define flush_output vmd_flush_output
#define gm_program_name vmd_gm_program_name
#define input vmd_input
#define INPUT_DEVICE VMD_INPUT_DEVICE
#define insert_note vmd_insert_note
#define isolate_note vmd_isolate_note
#define JOIN VMD_JOIN
#define JOIN3 VMD_JOIN3
#define LENGTH VMD_LENGTH
#define magic_mthd vmd_magic_mthd
#define magic_mtrk vmd_magic_mtrk
#define magic_vomid vmd_magic_vomid
#define map_add vmd_map_add
#define map_bstdata_t vmd_map_bstdata_t
#define map_copy vmd_map_copy
#define map_eq vmd_map_eq
#define map_fini vmd_map_fini
#define map_get vmd_map_get
#define map_get_change vmd_map_get_change
#define map_init vmd_map_init
#define map_print vmd_map_print
#define map_set vmd_map_set
#define map_set_node vmd_map_set_node
#define map_set_range vmd_map_set_range
#define map_t vmd_map_t
#define map_time vmd_map_time
#define map_value vmd_map_value
#define MAX VMD_MAX
#define MAX3 VMD_MAX3
#define MAX_PITCH VMD_MAX_PITCH
#define MAX_TIME VMD_MAX_TIME
#define MAX_TRACKS VMD_MAX_TRACKS
#define measure_clb_t vmd_measure_clb_t
#define measure_t vmd_measure_t
#define META_EOT VMD_META_EOT
#define META_PROPRIETARY VMD_META_PROPRIETARY
#define METAS VMD_METAS
#define META_TEMPO VMD_META_TEMPO
#define META_TIMESIG VMD_META_TIMESIG
#define META_TRACKNAME VMD_META_TRACKNAME
#define midi_eot vmd_midi_eot
#define midi_fwrite_meta vmd_midi_fwrite_meta
#define midi_fwrite_meta_header vmd_midi_fwrite_meta_header
#define midi_fwrite_notesystem vmd_midi_fwrite_notesystem
#define midi_fwrite_pitch vmd_midi_fwrite_pitch
#define midi_fwrite_propr vmd_midi_fwrite_propr
#define midi_fwrite_varlen vmd_midi_fwrite_varlen
#define midipitch_t vmd_midipitch_t
#define midi_write_meta vmd_midi_write_meta
#define midi_write_noteoff vmd_midi_write_noteoff
#define midi_write_noteon vmd_midi_write_noteon
#define MIN VMD_MIN
#define MIN3 VMD_MIN3
#define note_callback_t vmd_note_callback_t
#define note_clb_t vmd_note_clb_t
#define note_cmp vmd_note_cmp
#define note_reset_pitch vmd_note_reset_pitch
#define NOTES VMD_NOTES
#define note_set_cctrl vmd_note_set_cctrl
#define note_set_channel vmd_note_set_channel
#define note_set_pitch vmd_note_set_pitch
#define notes_off vmd_notes_off
#define notesystem_fini vmd_notesystem_fini
#define notesystem_import vmd_notesystem_import
#define notesystem_import_f vmd_notesystem_import_f
#define notesystem_is_midistd vmd_notesystem_is_midistd
#define notesystem_level2pitch vmd_notesystem_level2pitch
#define notesystem_levels vmd_notesystem_levels
#define notesystem_midistd vmd_notesystem_midistd
#define notesystem_pitch2level vmd_notesystem_pitch2level
#define notesystem_t vmd_notesystem_t
#define notesystem_tet vmd_notesystem_tet
#define note_t vmd_note_t
#define OK VMD_OK
#define output vmd_output
#define OUTPUT_DEVICE VMD_OUTPUT_DEVICE
#define pitch_info vmd_pitch_info
#define pitch_t vmd_pitch_t
#define platform_t vmd_platform_t
#define pool_alloc vmd_pool_alloc
#define pool_chunk_t vmd_pool_chunk_t
#define pool_fini vmd_pool_fini
#define pool_init vmd_pool_init
#define pool_strdup vmd_pool_strdup
#define pool_t vmd_pool_t
#define PROGRAMS VMD_PROGRAMS
#define PROPR_NOTESYSTEM VMD_PROPR_NOTESYSTEM
#define PROPR_PITCH VMD_PROPR_PITCH
#define PROPR_SHA VMD_PROPR_SHA
#define rendersystem_t vmd_rendersystem_t
#define reset_output vmd_reset_output
#define set_device vmd_set_device
#define SHA1_SIZE VMD_SHA1_SIZE
#define sleep vmd_sleep
#define sleep_till vmd_sleep_till
#define stack_block_t vmd_stack_block_t
#define stack_fini vmd_stack_fini
#define stack_init vmd_stack_init
#define stack_pop vmd_stack_pop
#define stack_push vmd_stack_push
#define stack_t vmd_stack_t
#define status_t vmd_status_t
#define STOP VMD_STOP
#define STRINGIFY VMD_STRINGIFY
#define SWAP VMD_SWAP
#define systime vmd_systime
#define systime2time vmd_systime2time
#define systime_t vmd_systime_t
#define TCTRL_BALANCE VMD_TCTRL_BALANCE
#define TCTRL_EXPRESSION VMD_TCTRL_EXPRESSION
#define tctrl_info vmd_tctrl_info
#define TCTRLS VMD_TCTRLS
#define TEMPO_BPM VMD_TEMPO_BPM
#define TEMPO_MIDI VMD_TEMPO_MIDI
#define test_fail vmd_test_fail
#define tevent_clb_t vmd_tevent_clb_t
#define time2systime vmd_time2systime
#define TIMESIG VMD_TIMESIG
#define timesig_construct vmd_timesig_construct
#define TIMESIG_DENOM VMD_TIMESIG_DENOM
#define TIMESIG_NUMER VMD_TIMESIG_NUMER
#define time_t vmd_time_t
#define track_clear vmd_track_clear
#define track_commit vmd_track_commit
#define track_create vmd_track_create
#define track_destroy vmd_track_destroy
#define track_fini vmd_track_fini
#define track_flatten vmd_track_flatten
#define track_for_range vmd_track_for_range
#define track_get_program vmd_track_get_program
#define track_idx vmd_track_idx
#define track_init vmd_track_init
#define track_insert vmd_track_insert
#define track_is_drums vmd_track_is_drums
#define track_length vmd_track_length
#define track_note vmd_track_note
#define track_note_t vmd_track_note_t
#define track_range vmd_track_range
#define track_rev_t vmd_track_rev_t
#define track_set_notesystem vmd_track_set_notesystem
#define track_set_program vmd_track_set_program
#define track_t vmd_track_t
#define track_temp_channel vmd_track_temp_channel
#define track_update vmd_track_update
#define TRUE VMD_TRUE
#define tvalue_info vmd_tvalue_info
#define TVALUE_PAN VMD_TVALUE_PAN
#define TVALUES VMD_TVALUES
#define TVALUE_VOLUME VMD_TVALUE_VOLUME
#define velocity_t vmd_velocity_t
#define VOICE_CHANNELPRESSURE VMD_VOICE_CHANNELPRESSURE
#define VOICE_CONTROLLER VMD_VOICE_CONTROLLER
#define VOICE_NOTEAFTERTOUCH VMD_VOICE_NOTEAFTERTOUCH
#define VOICE_NOTEOFF VMD_VOICE_NOTEOFF
#define VOICE_NOTEON VMD_VOICE_NOTEON
#define VOICE_PITCHWHEEL VMD_VOICE_PITCHWHEEL
#define VOICE_PROGRAM VMD_VOICE_PROGRAM
