macro (process_tests)
	set (TESTS_HEADER ${PROJECT_BINARY_DIR}/tests.h)
	include_directories (${PROJECT_BINARY_DIR})

	set (TEST_SOURCES ${ARGN})
	add_executable (tester ${TEST_SOURCES} ../main.c)
	target_link_libraries (tester libvomid)

	file (REMOVE ${TESTS_HEADER})
	list (FIND TEST_SOURCES setup.c SETUP_POS)
	list (FIND TEST_SOURCES teardown.c TEARDOWN_POS)
	list (REMOVE_ITEM TEST_SOURCES setup.c teardown.c)

	if (NOT ${SETUP_POS} EQUAL -1)
		file (APPEND ${TESTS_HEADER} "SETUP;\n")
	endif ()
	foreach (TEST_SOURCE ${TEST_SOURCES})
		string (REGEX REPLACE "\\.c$" "" TEST ${TEST_SOURCE})
		add_test (${TEST} tester ${TEST})
		file (APPEND ${TESTS_HEADER} "TEST(${TEST});\n")
	endforeach()
	if (NOT ${TEARDOWN_POS} EQUAL -1)
		file (APPEND ${TESTS_HEADER} "TEARDOWN;\n")
	endif ()
endmacro()
